language: c++
os: 
  - windows
install: 
  - export msbuild="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe"
  - powershell -Command wget "http://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-6_5_8/ACE-6.5.8.zip" -OutFile "ACE.zip"
  - powershell -Command Expand-Archive -LiteralPath ACE.zip -DestinationPath .
  - powershell -Command rm Ace.zip
  - powershell -Command Get-ChildItem -Path .
  - echo '#include "ace/config-win32.h"' > ./ACE_wrappers/ace/config.h
  - powershell -Command wget "https://github.com/oneapi-src/oneTBB/releases/download/v2020.2/tbb-2020.2-win.zip" -OutFile "tbb.zip"
  - powershell -Command Expand-Archive -LiteralPath tbb.zip -DestinationPath .
  - powershell -Command rm tbb.zip
#  - choco install visualstudio2019community
#  - choco install visualstudio2019-workload-nativedesktop
#  - export VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools"
  - export ACE_ROOT="/c/Users/travis/core-windows/ACE_wrappers"  
  - export TBB_ROOT_DIR="/c/Users/travis/core-windows/tbb"

script:
  - cmd
  - 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe' 'C:\Users\travis\build\tonymmm1\core-windows\ACE_wrappers\ACE_wrappers_vs2017.sln' -property:Configuration=Release -property:Platform=x64 -v:d
  - exit
  - mkdir build
  - cd build
  - cmake -DDEBUG=0 ..
  - cmd 
  - 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe' 'C:\Users\travis\build\tonymmm1\core-windows\build\MaNGOS.sln' -property:Configuration=Release -property:Platform=x64 -v:d -target:ALL_BUILD
