language: cpp
os: 
  - windows
#  - linux
#find libace dependency and or make script
install: 
  - choco feature enable -n allowEmptyChecksums
  - choco install tbb
  - choco install cmake
  - choco install git
  - choco install visualstudio2019community
  - choco install visualstudio2019-workload-nativedesktop
  - export VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools"
